package CalculatorJS.behavior;

/*Generated by MPS */

import org.mar9000.mps.ecmascript.behavior.JSExpression_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class InputFieldReference_BehaviorDescriptor extends JSExpression_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "CalculatorJS.structure.InputFieldReference";
  }

}
