package CalculatorJS.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_Calculator = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_InputField = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_InputFieldReference = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_OutputField = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Calculator:
        return props_Calculator;
      case LanguageConceptSwitch.InputField:
        return props_InputField;
      case LanguageConceptSwitch.InputFieldReference:
        return props_InputFieldReference;
      case LanguageConceptSwitch.OutputField:
        return props_OutputField;
    }
    return null;
  }
}
