package CalculatorJS.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptCalculator = new ConceptDescriptorBuilder("CalculatorJS.structure.Calculator", MetaIdFactory.conceptId(0x73f4da510e3e448cL, 0xa68b428ef5388ac7L, 0x1c0cfa9a1cc95c07L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(5843916997827683086L, "inputField", MetaIdFactory.conceptId(0x73f4da510e3e448cL, 0xa68b428ef5388ac7L, 0x5119c38c1062e2e4L), true, true, false), new ConceptDescriptorBuilder.Link(5843916997827683160L, "outputField", MetaIdFactory.conceptId(0x73f4da510e3e448cL, 0xa68b428ef5388ac7L, 0x5119c38c1062e310L), true, true, false)).children(new String[]{"inputField", "outputField"}, new boolean[]{true, true}).alias("calculator", "").create();
  /*package*/ final ConceptDescriptor myConceptInputField = new ConceptDescriptorBuilder("CalculatorJS.structure.InputField", MetaIdFactory.conceptId(0x73f4da510e3e448cL, 0xa68b428ef5388ac7L, 0x5119c38c1062e2e4L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).alias("input field", "").create();
  /*package*/ final ConceptDescriptor myConceptInputFieldReference = new ConceptDescriptorBuilder("CalculatorJS.structure.InputFieldReference", MetaIdFactory.conceptId(0x73f4da510e3e448cL, 0xa68b428ef5388ac7L, 0x5119c38c10631080L)).super_("org.mar9000.mps.ecmascript.structure.JSExpression").super_(MetaIdFactory.conceptId(0xa48297046b1b4b3fL, 0x8122a4a2e6ac90ffL, 0x76eb757dfbac2099L)).parents("org.mar9000.mps.ecmascript.structure.JSExpression").parentIds(MetaIdFactory.conceptId(0xa48297046b1b4b3fL, 0x8122a4a2e6ac90ffL, 0x76eb757dfbac2099L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(5843916997827694721L, "target", MetaIdFactory.conceptId(0x73f4da510e3e448cL, 0xa68b428ef5388ac7L, 0x5119c38c1062e2e4L), false)).references("target").create();
  /*package*/ final ConceptDescriptor myConceptOutputField = new ConceptDescriptorBuilder("CalculatorJS.structure.OutputField", MetaIdFactory.conceptId(0x73f4da510e3e448cL, 0xa68b428ef5388ac7L, 0x5119c38c1062e310L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(5843916997827683091L, "value", MetaIdFactory.conceptId(0xa48297046b1b4b3fL, 0x8122a4a2e6ac90ffL, 0x76eb757dfbac2099L), false, false, false)).children(new String[]{"value"}, new boolean[]{false}).alias("output field", "").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCalculator, myConceptInputField, myConceptInputFieldReference, myConceptOutputField);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0i, conceptFqName)) {
      case 0:
        return myConceptCalculator;
      case 1:
        return myConceptInputField;
      case 2:
        return myConceptInputFieldReference;
      case 3:
        return myConceptOutputField;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0i = new String[]{"CalculatorJS.structure.Calculator", "CalculatorJS.structure.InputField", "CalculatorJS.structure.InputFieldReference", "CalculatorJS.structure.OutputField"};
}
